package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/yanjiulab/packetforge/pkg/pdl"
)

func newGenCmd() *cobra.Command {
	var protoDir, outDir, lang string
	var includeBuiltin bool
	var expandBuiltinHeads bool
	cmd := &cobra.Command{
		Use:   "gen",
		Short: "Generate struct definitions from PDL",
		RunE: func(cmd *cobra.Command, args []string) error {
			protos, structs, err := loadPDLForGen(protoDir, includeBuiltin)
			if err != nil {
				return err
			}
			if len(protos) == 0 && len(structs) == 0 {
				return fmt.Errorf("no protocol/struct definitions found in %q", protoDir)
			}

			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return fmt.Errorf("create output dir: %w", err)
			}

			targets := []string{strings.ToLower(lang)}
			if strings.EqualFold(lang, "all") {
				targets = []string{"go", "c", "cpp"}
			}
			for _, t := range targets {
				var content, name string
				switch t {
				case "go":
					name = "pdl_gen.go"
					content = renderGo(protos, structs, expandBuiltinHeads)
				case "c":
					name = "pdl_gen.h"
					content = renderC(protos, structs, expandBuiltinHeads)
				case "cpp":
					name = "pdl_gen.hpp"
					content = renderCPP(protos, structs, expandBuiltinHeads)
					outPath := filepath.Join(outDir, name)
					if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
						return fmt.Errorf("write %s: %w", outPath, err)
					}
					fmt.Printf("generated: %s\n", outPath)
					codecName := "pdl_gen_codec.hpp"
					codecContent := renderCPPCodecFile(protos, structs, expandBuiltinHeads)
					codecPath := filepath.Join(outDir, codecName)
					if err := os.WriteFile(codecPath, []byte(codecContent), 0o644); err != nil {
						return fmt.Errorf("write %s: %w", codecPath, err)
					}
					fmt.Printf("generated: %s\n", codecPath)
					continue
				default:
					return fmt.Errorf("unsupported lang %q, expected one of: go,c,cpp,all", t)
				}
				outPath := filepath.Join(outDir, name)
				if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
					return fmt.Errorf("write %s: %w", outPath, err)
				}
				fmt.Printf("generated: %s\n", outPath)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&protoDir, "proto", "p", "proto", "Protocol definition directory (.pdl files)")
	cmd.Flags().StringVarP(&outDir, "out", "o", "generated", "Output directory")
	cmd.Flags().StringVar(&lang, "lang", "go", "Target language: go|c|cpp|all")
	cmd.Flags().BoolVarP(&includeBuiltin, "builtin-proto", "b", false, "Include built-in protocol definitions")
	cmd.Flags().BoolVar(&expandBuiltinHeads, "expand-builtin-heads", false, "Expand builtin head fields (mac/ipv4/ipv6) to raw arrays instead of named types")
	return cmd
}

func loadPDLForGen(dir string, includeBuiltin bool) ([]*pdl.Protocol, []*pdl.Struct, error) {
	reg := pdl.NewRegistry()
	if includeBuiltin {
		if err := reg.LoadBuiltinCommonProtocols(); err != nil {
			return nil, nil, fmt.Errorf("load builtin protocols: %w", err)
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, fmt.Errorf("read proto dir %q: %w", dir, err)
	}

	protoByName := map[string]*pdl.Protocol{}
	structByName := map[string]*pdl.Struct{}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".pdl" {
			continue
		}
		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, nil, fmt.Errorf("read %s: %w", path, err)
		}
		ps := pdl.NewParser(string(data))
		protos, structs, err := ps.ParseFile()
		if err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, st := range structs {
			structByName[strings.ToLower(st.Name)] = st
		}
		for _, pr := range protos {
			protoByName[strings.ToLower(pr.Name)] = pr
		}
	}
	if includeBuiltin {
		for _, name := range reg.List() {
			if _, ok := protoByName[strings.ToLower(name)]; ok {
				continue
			}
			if p := reg.Get(name); p != nil {
				protoByName[strings.ToLower(name)] = p
			}
		}
	}

	protoNames := make([]string, 0, len(protoByName))
	for k := range protoByName {
		protoNames = append(protoNames, k)
	}
	sort.Strings(protoNames)
	structNames := make([]string, 0, len(structByName))
	for k := range structByName {
		structNames = append(structNames, k)
	}
	sort.Strings(structNames)

	outProtos := make([]*pdl.Protocol, 0, len(protoNames))
	for _, k := range protoNames {
		outProtos = append(outProtos, protoByName[k])
	}
	outStructs := make([]*pdl.Struct, 0, len(structNames))
	for _, k := range structNames {
		outStructs = append(outStructs, structByName[k])
	}
	return outProtos, outStructs, nil
}

func renderGo(protos []*pdl.Protocol, structs []*pdl.Struct, expandBuiltinHeads bool) string {
	var b strings.Builder
	b.WriteString("// Code generated by packetforge pf gen; DO NOT EDIT.\n\n")
	b.WriteString("package generated\n\n")
	if !expandBuiltinHeads {
		b.WriteString("type Mac [6]byte\n")
		b.WriteString("type IPv4 [4]byte\n")
		b.WriteString("type IPv6 [16]byte\n\n")
	}
	for _, st := range structs {
		renderGoType(&b, st.Name, st.Fields, expandBuiltinHeads)
	}
	for _, pr := range protos {
		renderGoType(&b, pr.Name, pr.Fields, expandBuiltinHeads)
	}
	return b.String()
}

func renderGoType(b *strings.Builder, name string, fields []*pdl.Field, expandBuiltinHeads bool) {
	fmt.Fprintf(b, "type %s struct {\n", goName(name))
	for _, f := range fields {
		t, comment, ok := goFieldType(f, expandBuiltinHeads)
		if !ok {
			fmt.Fprintf(b, "\t// TODO unsupported field %s (%s)\n", f.Name, fieldDesc(f))
			continue
		}
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", goName(f.Name), t, f.Name)
		if comment != "" {
			fmt.Fprintf(b, "\t// %s\n", comment)
		}
	}
	b.WriteString("}\n\n")
}

func renderC(protos []*pdl.Protocol, structs []*pdl.Struct, expandBuiltinHeads bool) string {
	var b strings.Builder
	b.WriteString("/* Code generated by packetforge pf gen; DO NOT EDIT. */\n")
	b.WriteString("#pragma once\n\n#include <stdint.h>\n#include <stddef.h>\n\n")
	if !expandBuiltinHeads {
		b.WriteString("typedef uint8_t Mac[6];\n")
		b.WriteString("typedef uint8_t IPv4[4];\n")
		b.WriteString("typedef uint8_t IPv6[16];\n\n")
	}
	for _, st := range structs {
		renderCType(&b, st.Name, st.Fields, expandBuiltinHeads)
	}
	for _, pr := range protos {
		renderCType(&b, pr.Name, pr.Fields, expandBuiltinHeads)
	}
	return b.String()
}

func renderCPP(protos []*pdl.Protocol, structs []*pdl.Struct, expandBuiltinHeads bool) string {
	var b strings.Builder
	b.WriteString("// Code generated by packetforge pf gen; DO NOT EDIT.\n")
	b.WriteString("#pragma once\n\n#include <array>\n#include <cstddef>\n#include <cstdint>\n#include <vector>\n\n")
	if !expandBuiltinHeads {
		b.WriteString("struct Mac { std::uint8_t bytes[6]{}; };\n")
		b.WriteString("struct IPv4 { std::uint8_t bytes[4]{}; };\n")
		b.WriteString("struct IPv6 { std::uint8_t bytes[16]{}; };\n\n")
	}
	for _, st := range structs {
		renderCPPType(&b, st.Name, st.Fields, expandBuiltinHeads)
	}
	for _, pr := range protos {
		renderCPPType(&b, pr.Name, pr.Fields, expandBuiltinHeads)
	}
	return b.String()
}

func renderCPPCodecFile(protos []*pdl.Protocol, structs []*pdl.Struct, expandBuiltinHeads bool) string {
	var b strings.Builder
	b.WriteString("// Code generated by packetforge pf gen; DO NOT EDIT.\n")
	b.WriteString("#pragma once\n\n#include \"pdl_gen.hpp\"\n")
	b.WriteString("#include <type_traits>\n\n")
	b.WriteString("// Usage example:\n")
	b.WriteString("//   Sisl msg{};\n")
	b.WriteString("//   msg.metric_count = 1;\n")
	b.WriteString("//   msg.metrics.push_back(Metric{});\n")
	b.WriteString("//   std::vector<std::uint8_t> bytes;\n")
	b.WriteString("//   if (!pdl_codec::Serialize(msg, bytes)) { /* handle error */ }\n")
	b.WriteString("//\n")
	b.WriteString("//   Sisl parsed{};\n")
	b.WriteString("//   std::size_t off = 0;\n")
	b.WriteString("//   if (!pdl_codec::Deserialize(bytes.data(), bytes.size(), off, parsed)) { /* handle error */ }\n")
	b.WriteString("//   if (off != bytes.size()) { /* trailing bytes */ }\n\n")
	defs := make([]cppDef, 0, len(structs)+len(protos))
	for _, st := range structs {
		defs = append(defs, cppDef{Name: st.Name, Fields: st.Fields})
	}
	for _, pr := range protos {
		defs = append(defs, cppDef{Name: pr.Name, Fields: pr.Fields})
	}
	renderCPPCodec(&b, defs, expandBuiltinHeads)
	return b.String()
}

func renderCType(b *strings.Builder, name string, fields []*pdl.Field, expandBuiltinHeads bool) {
	typeName := goName(name)
	fmt.Fprintf(b, "typedef struct %s {\n", typeName)
	wrote := false
	for _, f := range fields {
		t, comment, ok := cFieldType(f, expandBuiltinHeads)
		if !ok {
			fmt.Fprintf(b, "    /* TODO unsupported field %s (%s) */\n", f.Name, fieldDesc(f))
			continue
		}
		fmt.Fprintf(b, "    %s\n", cDecl(t, cName(f.Name)))
		if f.Array == pdl.ArrayDynamic {
			fmt.Fprintf(b, "    size_t %s_len;\n", cName(f.Name))
		}
		if comment != "" {
			fmt.Fprintf(b, "    /* %s */\n", comment)
		}
		wrote = true
	}
	if !wrote {
		b.WriteString("    uint8_t _reserved;\n")
	}
	fmt.Fprintf(b, "} %s;\n\n", typeName)
}

func renderCPPType(b *strings.Builder, name string, fields []*pdl.Field, expandBuiltinHeads bool) {
	typeName := goName(name)
	fmt.Fprintf(b, "struct %s {\n", typeName)
	wrote := false
	for _, f := range fields {
		t, comment, ok := cppFieldType(f, expandBuiltinHeads)
		if !ok {
			fmt.Fprintf(b, "    // TODO unsupported field %s (%s)\n", f.Name, fieldDesc(f))
			continue
		}
		fmt.Fprintf(b, "    %s\n", cppDecl(t, cName(f.Name)))
		if comment != "" {
			fmt.Fprintf(b, "    // %s\n", comment)
		}
		wrote = true
	}
	if !wrote {
		b.WriteString("    std::uint8_t _reserved{};\n")
	}
	b.WriteString("};\n\n")
}

func goFieldType(f *pdl.Field, expandBuiltinHeads bool) (string, string, bool) {
	base, ok := goBaseType(f, expandBuiltinHeads)
	if !ok {
		return "", "", false
	}
	switch f.Array {
	case pdl.ArrayNone:
		return base, "", true
	case pdl.ArrayFixed:
		return fmt.Sprintf("[%d]%s", f.ArrayLen, base), "", true
	case pdl.ArrayDynamic:
		return "[]" + base, "dynamic array", true
	case pdl.ArrayField:
		return "[]" + base, "array length depends on field " + f.ArrayLenField, true
	default:
		return "", "", false
	}
}

func cFieldType(f *pdl.Field, expandBuiltinHeads bool) (string, string, bool) {
	if f.Array == pdl.ArrayNone {
		switch f.Type {
		case pdl.TypeMAC:
			if expandBuiltinHeads {
				return "uint8_t[6]", "", true
			}
			return "Mac", "", true
		case pdl.TypeIPv4:
			if expandBuiltinHeads {
				return "uint8_t[4]", "", true
			}
			return "IPv4", "", true
		case pdl.TypeIPv6:
			if expandBuiltinHeads {
				return "uint8_t[16]", "", true
			}
			return "IPv6", "", true
		}
	}
	base, ok := cBaseType(f, expandBuiltinHeads)
	if !ok {
		return "", "", false
	}
	switch f.Array {
	case pdl.ArrayNone:
		return base, "", true
	case pdl.ArrayFixed:
		return fmt.Sprintf("%s[%d]", base, f.ArrayLen), "", true
	case pdl.ArrayDynamic:
		return base + "*", "dynamic array, length field: " + cName(f.Name) + "_len", true
	case pdl.ArrayField:
		return base + "*", "array length depends on field " + f.ArrayLenField, true
	default:
		return "", "", false
	}
}

func cppFieldType(f *pdl.Field, expandBuiltinHeads bool) (string, string, bool) {
	if f.Array == pdl.ArrayNone {
		switch f.Type {
		case pdl.TypeMAC:
			if expandBuiltinHeads {
				return "std::uint8_t[6]", "", true
			}
			return "Mac", "", true
		case pdl.TypeIPv4:
			if expandBuiltinHeads {
				return "std::uint8_t[4]", "", true
			}
			return "IPv4", "", true
		case pdl.TypeIPv6:
			if expandBuiltinHeads {
				return "std::uint8_t[16]", "", true
			}
			return "IPv6", "", true
		}
	}
	base, ok := cppBaseType(f, expandBuiltinHeads)
	if !ok {
		return "", "", false
	}
	switch f.Array {
	case pdl.ArrayNone:
		return base, "", true
	case pdl.ArrayFixed:
		return fmt.Sprintf("%s[%d]", base, f.ArrayLen), "", true
	case pdl.ArrayDynamic:
		return "std::vector<" + base + ">", "dynamic array", true
	case pdl.ArrayField:
		return "std::vector<" + base + ">", "array length depends on field " + f.ArrayLenField, true
	default:
		return "", "", false
	}
}

func goBaseType(f *pdl.Field, expandBuiltinHeads bool) (string, bool) {
	switch f.Type {
	case pdl.TypeU8:
		return "uint8", true
	case pdl.TypeU16:
		return "uint16", true
	case pdl.TypeU32:
		return "uint32", true
	case pdl.TypeU64:
		return "uint64", true
	case pdl.TypeMAC:
		if expandBuiltinHeads {
			return "[6]byte", true
		}
		return "Mac", true
	case pdl.TypeIPv4:
		if expandBuiltinHeads {
			return "[4]byte", true
		}
		return "IPv4", true
	case pdl.TypeIPv6:
		if expandBuiltinHeads {
			return "[16]byte", true
		}
		return "IPv6", true
	case pdl.TypeStructRef:
		return goName(f.StructName), true
	case pdl.TypeStructArray:
		return goName(f.StructName), true
	default:
		return "", false
	}
}

func cBaseType(f *pdl.Field, expandBuiltinHeads bool) (string, bool) {
	switch f.Type {
	case pdl.TypeU8:
		return "uint8_t", true
	case pdl.TypeU16:
		return "uint16_t", true
	case pdl.TypeU32:
		return "uint32_t", true
	case pdl.TypeU64:
		return "uint64_t", true
	case pdl.TypeMAC:
		if expandBuiltinHeads {
			return "uint8_t[6]", true
		}
		return "Mac", true
	case pdl.TypeIPv4:
		if expandBuiltinHeads {
			return "uint8_t[4]", true
		}
		return "IPv4", true
	case pdl.TypeIPv6:
		if expandBuiltinHeads {
			return "uint8_t[16]", true
		}
		return "IPv6", true
	case pdl.TypeStructRef:
		return goName(f.StructName), true
	case pdl.TypeStructArray:
		return goName(f.StructName), true
	default:
		return "", false
	}
}

func cppBaseType(f *pdl.Field, expandBuiltinHeads bool) (string, bool) {
	switch f.Type {
	case pdl.TypeU8:
		return "std::uint8_t", true
	case pdl.TypeU16:
		return "std::uint16_t", true
	case pdl.TypeU32:
		return "std::uint32_t", true
	case pdl.TypeU64:
		return "std::uint64_t", true
	case pdl.TypeMAC:
		if expandBuiltinHeads {
			return "std::array<std::uint8_t, 6>", true
		}
		return "Mac", true
	case pdl.TypeIPv4:
		if expandBuiltinHeads {
			return "std::array<std::uint8_t, 4>", true
		}
		return "IPv4", true
	case pdl.TypeIPv6:
		if expandBuiltinHeads {
			return "std::array<std::uint8_t, 16>", true
		}
		return "IPv6", true
	case pdl.TypeStructRef:
		return goName(f.StructName), true
	case pdl.TypeStructArray:
		return goName(f.StructName), true
	default:
		return "", false
	}
}

func fieldDesc(f *pdl.Field) string {
	switch f.Array {
	case pdl.ArrayDynamic:
		return "dynamic array"
	case pdl.ArrayField:
		return "array len by field " + f.ArrayLenField
	default:
		return "unsupported type"
	}
}

func goName(s string) string {
	parts := splitIdent(s)
	if len(parts) == 0 {
		return "X"
	}
	var out strings.Builder
	for _, p := range parts {
		out.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			out.WriteString(strings.ToLower(p[1:]))
		}
	}
	return out.String()
}

func cName(s string) string {
	parts := splitIdent(s)
	if len(parts) == 0 {
		return "x"
	}
	return strings.ToLower(strings.Join(parts, "_"))
}

func splitIdent(s string) []string {
	f := strings.FieldsFunc(s, func(r rune) bool {
		return !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'))
	})
	if len(f) == 0 {
		return nil
	}
	return f
}

func cDecl(t, name string) string {
	if i := strings.Index(t, "["); i > 0 {
		return fmt.Sprintf("%s %s%s;", t[:i], name, t[i:])
	}
	return fmt.Sprintf("%s %s;", t, name)
}

func cppDecl(t, name string) string {
	if i := strings.Index(t, "["); i > 0 {
		return fmt.Sprintf("%s %s%s{};", t[:i], name, t[i:])
	}
	return fmt.Sprintf("%s %s{};", t, name)
}

type cppDef struct {
	Name   string
	Fields []*pdl.Field
}

func renderCPPCodec(b *strings.Builder, defs []cppDef, expandBuiltinHeads bool) {
	b.WriteString("namespace pdl_codec {\n\n")
	b.WriteString("inline void WriteU8(std::vector<std::uint8_t>& out, std::uint8_t v) { out.push_back(v); }\n")
	b.WriteString("inline void WriteU16(std::vector<std::uint8_t>& out, std::uint16_t v) { out.push_back(static_cast<std::uint8_t>((v >> 8) & 0xFF)); out.push_back(static_cast<std::uint8_t>(v & 0xFF)); }\n")
	b.WriteString("inline void WriteU32(std::vector<std::uint8_t>& out, std::uint32_t v) { for (int i = 3; i >= 0; --i) out.push_back(static_cast<std::uint8_t>((v >> (i * 8)) & 0xFF)); }\n")
	b.WriteString("inline void WriteU64(std::vector<std::uint8_t>& out, std::uint64_t v) { for (int i = 7; i >= 0; --i) out.push_back(static_cast<std::uint8_t>((v >> (i * 8)) & 0xFF)); }\n")
	b.WriteString("inline bool ReadU8(const std::uint8_t* data, std::size_t len, std::size_t& off, std::uint8_t& v) { if (off + 1 > len) return false; v = data[off++]; return true; }\n")
	b.WriteString("inline bool ReadU16(const std::uint8_t* data, std::size_t len, std::size_t& off, std::uint16_t& v) { if (off + 2 > len) return false; v = (static_cast<std::uint16_t>(data[off]) << 8) | data[off+1]; off += 2; return true; }\n")
	b.WriteString("inline bool ReadU32(const std::uint8_t* data, std::size_t len, std::size_t& off, std::uint32_t& v) { if (off + 4 > len) return false; v = (static_cast<std::uint32_t>(data[off]) << 24) | (static_cast<std::uint32_t>(data[off+1]) << 16) | (static_cast<std::uint32_t>(data[off+2]) << 8) | data[off+3]; off += 4; return true; }\n")
	b.WriteString("inline bool ReadU64(const std::uint8_t* data, std::size_t len, std::size_t& off, std::uint64_t& v) { if (off + 8 > len) return false; v = 0; for (int i = 0; i < 8; ++i) { v = (v << 8) | data[off+i]; } off += 8; return true; }\n")
	b.WriteString("inline void WriteBytes(std::vector<std::uint8_t>& out, const std::uint8_t* p, std::size_t n) { out.insert(out.end(), p, p + n); }\n")
	b.WriteString("inline bool ReadBytes(const std::uint8_t* data, std::size_t len, std::size_t& off, std::uint8_t* dst, std::size_t n) { if (off + n > len) return false; for (std::size_t i = 0; i < n; ++i) dst[i] = data[off+i]; off += n; return true; }\n\n")

	for _, d := range defs {
		fmt.Fprintf(b, "inline bool Serialize(const %s& in, std::vector<std::uint8_t>& out);\n", goName(d.Name))
		fmt.Fprintf(b, "inline bool Deserialize(const std::uint8_t* data, std::size_t len, std::size_t& off, %s& out);\n", goName(d.Name))
	}
	b.WriteString("\n")

	for _, d := range defs {
		typeName := goName(d.Name)
		fmt.Fprintf(b, "inline bool Serialize(const %s& in, std::vector<std::uint8_t>& out) {\n", typeName)
		for _, f := range d.Fields {
			field := "in." + cName(f.Name)
			b.WriteString(cppEmitSerializeField(f, field, expandBuiltinHeads, "in."))
		}
		b.WriteString("    return true;\n}\n\n")

		fmt.Fprintf(b, "inline bool Deserialize(const std::uint8_t* data, std::size_t len, std::size_t& off, %s& out) {\n", typeName)
		for i, f := range d.Fields {
			field := "out." + cName(f.Name)
			isLast := i == len(d.Fields)-1
			b.WriteString(cppEmitDeserializeField(f, field, expandBuiltinHeads, "out.", isLast))
		}
		b.WriteString("    return true;\n}\n\n")
	}
	b.WriteString("} // namespace pdl_codec\n")
}

func cppEmitSerializeField(f *pdl.Field, expr string, expandBuiltinHeads bool, root string) string {
	var b strings.Builder
	switch f.Array {
	case pdl.ArrayNone:
		b.WriteString(cppIndent(cppEmitSerializeElem(f, expr, expandBuiltinHeads), "    "))
	case pdl.ArrayFixed:
		b.WriteString(fmt.Sprintf("    for (std::size_t i = 0; i < %d; ++i) {\n", f.ArrayLen))
		b.WriteString(cppIndent(cppEmitSerializeElem(f, expr+"[i]", expandBuiltinHeads), "        "))
		b.WriteString("    }\n")
	case pdl.ArrayDynamic:
		b.WriteString(fmt.Sprintf("    for (const auto& elem : %s) {\n", expr))
		b.WriteString(cppIndent(cppEmitSerializeElem(f, "elem", expandBuiltinHeads), "        "))
		b.WriteString("    }\n")
	case pdl.ArrayField:
		b.WriteString(fmt.Sprintf("    if (static_cast<std::size_t>(%s%s) != %s.size()) return false;\n", root, cName(f.ArrayLenField), expr))
		b.WriteString(fmt.Sprintf("    for (const auto& elem : %s) {\n", expr))
		b.WriteString(cppIndent(cppEmitSerializeElem(f, "elem", expandBuiltinHeads), "        "))
		b.WriteString("    }\n")
	}
	return b.String()
}

func cppEmitDeserializeField(f *pdl.Field, expr string, expandBuiltinHeads bool, root string, isLast bool) string {
	var b strings.Builder
	switch f.Array {
	case pdl.ArrayNone:
		b.WriteString(cppIndent(cppEmitDeserializeElem(f, expr, expandBuiltinHeads), "    "))
	case pdl.ArrayFixed:
		b.WriteString(fmt.Sprintf("    for (std::size_t i = 0; i < %d; ++i) {\n", f.ArrayLen))
		b.WriteString(cppIndent(cppEmitDeserializeElem(f, expr+"[i]", expandBuiltinHeads), "        "))
		b.WriteString("    }\n")
	case pdl.ArrayDynamic:
		if !isLast {
			b.WriteString("    // ambiguous []T not at tail; cannot safely deserialize\n")
			b.WriteString("    return false;\n")
			return b.String()
		}
		b.WriteString(fmt.Sprintf("    %s.clear();\n", expr))
		b.WriteString("    while (off < len) {\n")
		b.WriteString("        typename std::decay<decltype(" + expr + ")>::type::value_type elem{};\n")
		b.WriteString(cppIndent(cppEmitDeserializeElem(f, "elem", expandBuiltinHeads), "        "))
		b.WriteString("        " + expr + ".push_back(elem);\n")
		b.WriteString("    }\n")
	case pdl.ArrayField:
		b.WriteString(fmt.Sprintf("    %s.clear();\n", expr))
		b.WriteString(fmt.Sprintf("    %s.reserve(static_cast<std::size_t>(%s%s));\n", expr, root, cName(f.ArrayLenField)))
		b.WriteString(fmt.Sprintf("    for (std::size_t i = 0; i < static_cast<std::size_t>(%s%s); ++i) {\n", root, cName(f.ArrayLenField)))
		b.WriteString("        typename std::decay<decltype(" + expr + ")>::type::value_type elem{};\n")
		b.WriteString(cppIndent(cppEmitDeserializeElem(f, "elem", expandBuiltinHeads), "        "))
		b.WriteString("        " + expr + ".push_back(elem);\n")
		b.WriteString("    }\n")
	}
	return b.String()
}

func cppEmitSerializeElem(f *pdl.Field, expr string, expandBuiltinHeads bool) string {
	switch f.Type {
	case pdl.TypeU8:
		return "WriteU8(out, " + expr + ");\n"
	case pdl.TypeU16:
		return "WriteU16(out, " + expr + ");\n"
	case pdl.TypeU32:
		return "WriteU32(out, " + expr + ");\n"
	case pdl.TypeU64:
		return "WriteU64(out, " + expr + ");\n"
	case pdl.TypeMAC:
		return fmt.Sprintf("WriteBytes(out, %s, 6);\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeIPv4:
		return fmt.Sprintf("WriteBytes(out, %s, 4);\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeIPv6:
		return fmt.Sprintf("WriteBytes(out, %s, 16);\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeStructRef, pdl.TypeStructArray:
		return "if (!Serialize(" + expr + ", out)) return false;\n"
	default:
		return "return false;\n"
	}
}

func cppEmitDeserializeElem(f *pdl.Field, expr string, expandBuiltinHeads bool) string {
	switch f.Type {
	case pdl.TypeU8:
		return "if (!ReadU8(data, len, off, " + expr + ")) return false;\n"
	case pdl.TypeU16:
		return "if (!ReadU16(data, len, off, " + expr + ")) return false;\n"
	case pdl.TypeU32:
		return "if (!ReadU32(data, len, off, " + expr + ")) return false;\n"
	case pdl.TypeU64:
		return "if (!ReadU64(data, len, off, " + expr + ")) return false;\n"
	case pdl.TypeMAC:
		return fmt.Sprintf("if (!ReadBytes(data, len, off, %s, 6)) return false;\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeIPv4:
		return fmt.Sprintf("if (!ReadBytes(data, len, off, %s, 4)) return false;\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeIPv6:
		return fmt.Sprintf("if (!ReadBytes(data, len, off, %s, 16)) return false;\n", cppBytePtrExpr(f, expr, expandBuiltinHeads))
	case pdl.TypeStructRef, pdl.TypeStructArray:
		return "if (!Deserialize(data, len, off, " + expr + ")) return false;\n"
	default:
		return "return false;\n"
	}
}

func cppBytePtrExpr(f *pdl.Field, expr string, expandBuiltinHeads bool) string {
	if expandBuiltinHeads {
		return expr + ".data()"
	}
	switch f.Type {
	case pdl.TypeMAC, pdl.TypeIPv4, pdl.TypeIPv6:
		return expr + ".bytes"
	default:
		return expr
	}
}

func cppIndent(s, p string) string {
	lines := strings.Split(s, "\n")
	for i, ln := range lines {
		if ln == "" {
			continue
		}
		lines[i] = p + ln
	}
	return strings.Join(lines, "\n")
}
